[project]
authors = ["alexey <alexnagornnyy.an@gmail.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = 'limit_orders'

[dependencies]
token_abi = { path = "../abi/token_abi" }

[constants]
AMOUNT_1 = { type = "u64", value = "200_000_000_000" }
ASSET_1 = { type = "Identity", value = "0x35395f5b21b3e93e0dd4e476bc8d92a989185cf050a71aff861667d5a1ddefe3" }
ORDER_OWNER = { type = "Identity", value = "0x5d99ee966b42cd8fc7bdd1364b389153a9e78b42b7d4a691470674e817888d4e" }
