name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Set this to your default branch if it's not master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14" # Set this to your project's node version

      - name: Install Dependencies
        run: npm install # or use yarn

      - name: Build Project
        run: npm run build # Replace with your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Set this to your build output directory
